name: Teste de Login FTP

on:
  workflow_dispatch:  # Permite rodar manualmente no GitHub

jobs:
  ftp-login:
    runs-on: ubuntu-latest
    steps:
      - name: Testando conexão FTP
        run: |
          echo "Conectando ao FTP..."
          curl -v --ftp-ssl -u ${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }} ftp://${{ secrets.FTP_SERVER }}:${{ secrets.FTP_PORT }}/ || echo "Erro de login"
